const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {JSDOM}=require('/tmp/jeu-validation/node_modules/jsdom');
const html=fs.readFileSync('index.html','utf8'),dom=new JSDOM(html,{runScripts:'outside-only',url:'http://localhost/'}),ctx=dom.getInternalVMContext();
dom.window.requestAnimationFrame=()=>1;dom.window.setTimeout=()=>1;dom.window.clearTimeout=()=>{};ctx.assert=assert;
try{
 for(const[,file]of html.matchAll(/<script src="([^"]+)"/g))vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
 vm.runInContext(`
  // Isoler les ventes et trajets des absences aléatoires de début de journée.
  startEventsDay = () => {};
  newGame();
  const fallback = nearestWalkable(ensurePersonalFallback()), seller = createEmployee('vendeur',fallback.x,fallback.y);
  game.employees.push(seller);normalizeEmployeePhysicalState(seller);
  const quantities = Object.fromEntries(Object.keys(PRODUCT_CONFIG).map(p=>[p, p==='Produit A'?3:0]));
  const networkBefore=getNetworkStock().total;
  assert.equal(setSellerLoad(seller,{...quantities,'Produit A':seller.capacity+1}).success,false);
  assert.equal(setSellerLoad(seller,quantities).success,true);
  assert.equal(getNetworkStock().total,networkBefore);
  assert.equal(seller.inventory['Produit A'],3);
  const deploymentGoal=mapData.navigation.nodes.find(n=>mapDistance(n,seller)>4&&mapDistance(n,seller)<8&&isWalkable(n));
  assert.equal(planSellerDeployment(seller,deploymentGoal).success,true);
  assert.equal(mapDistance(seller,fallback),0,'planification sans déplacement');
  assert.equal(confirmSellerDeployment(seller).success,true);
  assert.equal(confirmSellerDeployment(seller).success,false,'double confirmation refusée');
  assert.equal(getSalesPointForSeller(seller.id).active,false);
  updateSimulation(.1);assert.ok(mapDistance(seller,fallback)>0,'trajet pendant préparation');
  assert.equal(game.dayElapsed,0);assert.equal(customers.length,0);
  const pausedPosition={x:seller.x,y:seller.y};toggleSimulationPause();updateSimulation(1);
  assert.equal(mapDistance(seller,pausedPosition),0);toggleSimulationPause();
  const snapshot=createSaveSnapshot();restoreSaveSnapshot(snapshot);
  const restored=getEmployeeById(seller.id);assert.equal(mapDistance(restored,pausedPosition),0,'reprise sans téléportation');
  for(let i=0;i<1000&&restored.operationalState===EMPLOYEE_OPERATION.OUTBOUND;i++)updateSimulation(.1);
  assert.equal(restored.operationalState,EMPLOYEE_OPERATION.AT_POST);assert.ok(mapDistance(restored,deploymentGoal)<.1);
  assert.equal(getSalesPointForSeller(restored.id).active,true);
  const arrived={x:restored.x,y:restored.y};startDay();assert.equal(mapDistance(restored,arrived),0);
  assert.equal(restored.inventory['Produit A'],3,'pas de chargement automatique après choix explicite');
  clearWaitingCustomers();const automatic=createCustomer();
  Object.assign(automatic,{product:'Produit A',quantity:1,price:12,budget:20,...queueDestination(restored,0)});
  assert.equal(joinSellerQueue(automatic,restored),true);updateCustomersRealtime(.1);
  for(let i=0;i<100&&!automatic.saleResolved;i++)updateEmployeesRealtime(.1);
  assert.equal(automatic.saleResolved,true,'vente automatique après déploiement');
  assert.equal(restored.inventory['Produit A'],2);assert.equal(restored.money,12);
  clearWaitingCustomers();const reception=getPlayerSeller(),client=createCustomer();
  Object.assign(client,{product:'Produit A',quantity:1,price:12,budget:20,...queueDestination(reception,0)});
  assert.equal(joinSellerQueue(client,reception),true);updateCustomersRealtime(.1);
  assert.equal(client.state,'WAITING');const cash=game.money;
  assert.equal(resolveSale(client).success,true);assert.equal(game.money,cash+12);
  assert.equal(resolveSale(client).success,false);
  const courier=createEmployee('ravitailleur',arrived.x,arrived.y);game.employees.push(courier);
  setEmployeeOperation(courier,EMPLOYEE_OPERATION.AT_POST);
  assert.equal(requestStrategicEmployeeMove(courier,deploymentGoal).success,false,'rôle sans rattachement refusé');
  const malformed=createSaveSnapshot();malformed.game.employees[0].plannedSalesPosition={x:NaN,y:1};
  assert.throws(()=>validateSaveSnapshot(malformed));
  newGame();
  const notConfirmed=createEmployee('vendeur',fallback.x,fallback.y);game.employees.push(notConfirmed);normalizeEmployeePhysicalState(notConfirmed);
  assert.equal(setSellerLoad(notConfirmed,quantities).success,true);createSalesPoint(notConfirmed,deploymentGoal.x,deploymentGoal.y).active=false;
  startDay();assert.equal(notConfirmed.operationalState,EMPLOYEE_OPERATION.RESTING,'aucun départ sans confirmation');
  newGame(); assert.equal('playerX' in game,false);assert.equal('playerY' in game,false);assert.equal(createIsometricRenderState().entities.some(e=>e.type==='player'),false);assert.equal(requestPlayerMovement({x:50,y:50}),false);
  const home=createApartment('depot',34,35), employee=createEmployee('vendeur',34,35);employee.assignment.apartmentId=home.id;employee.assignment.manual=true;game.employees.push(employee);startDay();setEmployeeOperation(employee,EMPLOYEE_OPERATION.AT_POST);
  selectedEmployeeId=employee.id; const from={x:employee.x,y:employee.y}, goal=mapData.navigation.nodes.find(n=>mapDistance(n,employee)>8&&isWalkable(n));
  assert.equal(requestSelectedEmployeeMove({x:10,y:14}),false);assert.equal(requestSelectedEmployeeMove(goal),true);assert.equal(employee.operationalState,EMPLOYEE_OPERATION.MANUAL_ORDER);assert.deepEqual({x:employee.x,y:employee.y},from);
  let moved=false;for(let i=0;i<1200&&employee.operationalState===EMPLOYEE_OPERATION.MANUAL_ORDER;i++){const before={x:employee.x,y:employee.y};updateSimulation(.1);moved||=mapDistance(before,employee)>0;assert.ok(isWalkable(employee));}assert.ok(moved);assert.ok(mapDistance(employee,goal)<.1);
  assert.equal(employee.operationalWarning, '', 'un ordre réussi ne bloque pas le travail');
  assert.equal(canEmployeeOperate(employee), true, 'employé disponible après arrivée');
  const nextGoal=mapData.navigation.nodes.find(n=>mapDistance(n,employee)>8&&isWalkable(n));
  assert.equal(requestStrategicEmployeeMove(employee,nextGoal).success,true);
  const beforeSpeed=createSaveSnapshot();game.clock.speed=1;updateSimulation(.4);
  const one={x:employee.x,y:employee.y};restoreSaveSnapshot(beforeSpeed);game.clock.speed=2;updateSimulation(.2);
  assert.ok(mapDistance(one,getEmployeeById(employee.id))<1e-7,'x1 et x2 appliqués une seule fois');
  const oldSave=createSaveSnapshot();oldSave.version=7;oldSave.game.playerX=12;oldSave.game.playerY=18;oldSave.game.playerDestination={x:1,y:2};
  const oldStock=getNetworkStock().total;restoreSaveSnapshot(oldSave);
  assert.equal('playerX' in game,false);assert.equal('playerDestination' in game,false);assert.equal(getNetworkStock().total,oldStock);
  const stable=createSaveSnapshot();restoreSaveSnapshot(stable);assert.deepEqual(createSaveSnapshot(),stable,'migration idempotente');
 `,ctx);
 const atlas=JSON.parse(fs.readFileSync('assets/characters/v3/people.json'));assert.equal(atlas.meta.idleFrames,4);assert.equal(atlas.meta.walkFrames,6);assert.equal(atlas.meta.directions,8);assert.equal(Object.keys(atlas.frames).length,720);
 console.log('PASS deployment, stock, automatic/manual sales, pause/resume, role restrictions, playerless migration, x1/x2 and v3 atlas');
}finally{dom.window.close();}
