// Assertions ciblées, exécutées dans le même DOM que le parcours historique.
{
    const courier = createEmployee('ravitailleur', 50, 50);
    assert.equal(courier.capacity, 15); awardEmployeeExperience(courier, 40); assert.equal(courier.level, 3); assert.equal(courier.capacity, 22);
    awardEmployeeExperience(courier, 1000); assert.equal(courier.level, 5); assert.equal(courier.capacity, 30);
    const before = game.money; payDailySalaries(); const after = game.money;
    assert.ok(after < before); payDailySalaries(); assert.equal(game.money, after);
    assert.ok(getNetworkProblems().every(p => p.code && p.level && p.message && p.action));
    const seller = game.employees.find(e => e.role === 'vendeur');
    seller.salesRate['Produit A'] = 2 / 60; seller.inventory['Produit A'] = 8;
    assert.equal(estimateStockSeconds(seller, 'Produit A'), 240);
    const manager = game.employees.find(e => e.role === 'gerant');
    const team = { id: 'test-team', name: 'Nord', managerId: manager.id, sellerIds: [seller.id], courierIds: [], watcherIds: [], apartmentIds: [game.apartments[0].id] };
    assert.equal(configureTeam(team), true);
    const other = createEmployee('gerant', 50, 50); game.employees.push(other);
    assert.equal(configureTeam({ ...team, id: 'other', managerId: other.id }), false);
    const holder = { inventory: game.playerInventory, capacity: Infinity };
    assert.equal(transferInventory(holder, holder, 'Produit A', 1), false);
    const customer = { id: 'loyal', loyaltyId: 'loyal', satisfaction: 100, assignedSellerId: seller.id };
    const reputation = game.reputation;
    recordCustomerFeedback(customer, true); assert.ok(game.reputation >= reputation);
    const visits = game.customerLoyalty.find(r => r.id === 'loyal').visits;
    recordCustomerFeedback(customer, true); assert.equal(game.customerLoyalty.find(r => r.id === 'loyal').visits, visits);
    (game.events || []).slice().forEach(finishEvent);
    const price = getStockPurchasePrice('Produit A'); activateEvent('SUPPLIER_DISCOUNT', 2);
    assert.ok(getStockPurchasePrice('Produit A') < price); updateEventsRealtime(3); assert.equal(getStockPurchasePrice('Produit A'), price);
    const event = activateEvent('EMPLOYEE_ABSENT', 1);
    if (event) { assert.equal(getEmployeeById(event.employeeId).active, false); updateEventsRealtime(2); assert.equal(getEmployeeById(event.employeeId).active, true); }
    assert.equal(knowledgeLabel(80), 'IDENTIFIED');
    police.alerts.slice().forEach(a => a.element.remove()); police.alerts = [];
    const isolated = createEmployee('vendeur', 2, 2); isolated.state = 'en poste'; isolated.alertProtocol = 'mise-en-securite'; game.employees.push(isolated); createSalesPoint(isolated, 2, 2);
    const alert = createAlert('test', { x: 50, y: 50 }, 10, 1); updateAlerts(2);
    assert.equal(isolated.state, 'en poste'); assert.ok(alert.teamIds.includes('test-team'));
    updateAlerts(20); assert.equal(police.alerts.length, 0);
    const walker = { x: 5, y: 20 };
    const path = findMapPath(walker, { x: 33, y: 20 }); assert.ok(path.length > 1);
    for (let i = 0; i < 1500; i++) { const done = moveMapEntity(walker, { x: 33, y: 20 }, .1, 10); assert.ok(isWalkable(walker)); if (done) break; }
    assert.ok(mapDistance(walker, { x: 33, y: 20 }) < .1);
    assert.ok(mapData.apartmentSites.every(isWalkable)); assert.ok(mapData.strategicSalesSites.every(isWalkable));
    zoomCamera(100); assert.equal(camera.zoom, camera.max); zoomCamera(.00001); assert.equal(camera.zoom, camera.min);
    assert.equal(document.getElementById('customerPanel').parentNode.id, 'mapViewport');
    assert.equal(document.getElementById('topbar').parentNode.id, 'game');
    const cash = game.money; game.totalCustomers = 10;
    const capacity = game.apartments[0].capacity; assert.equal(purchaseUpgrade('apartment', game.apartments[0].id), true);
    assert.equal(game.apartments[0].capacity, capacity + 20); assert.equal(game.money, cash - 80);
    const remaining = getSupplierRemaining('Produit A'); assert.equal(buyStock('Produit A', remaining + 1, null), false);
    settleDailyEconomy(); const settled = game.totalNetProfit; settleDailyEconomy(); assert.equal(game.totalNetProfit, settled);
    const snapshot = createSaveSnapshot(), moneyBeforeSave = game.money, stockBeforeSave = getNetworkStock().total;
    assert.equal(saveGame(), true); game.money = 0; assert.equal(loadGame(), true);
    assert.equal(game.money, moneyBeforeSave); assert.equal(getNetworkStock().total, stockBeforeSave);
    const invalid = serializeState(snapshot); invalid.version = 999;
    assert.throws(() => restoreSaveSnapshot(invalid)); assert.equal(game.money, moneyBeforeSave);
    const corrupt = serializeState(snapshot); corrupt.game.playerInventory['Produit A'] = -1;
    assert.throws(() => restoreSaveSnapshot(corrupt)); assert.equal(getNetworkStock().total, stockBeforeSave);
    const legacy = serializeState(snapshot); legacy.version = 1; assert.equal(restoreSaveSnapshot(legacy), true);
    clearWaitingCustomers(); game.dayActive = true; game.logisticsRequests = []; game.logisticsMissions = [];
    const supplySeller = game.employees.find(e => e.role === 'vendeur'); supplySeller.active = true; supplySeller.state = 'en poste'; supplySeller.currentMissionId = null;
    supplySeller.inventory['Produit A'] = 0;
    const courierForSave = game.employees.find(e => e.role === 'ravitailleur'); courierForSave.state = 'en poste'; courierForSave.currentMissionId = null;
    const depotForSave = game.apartments[0]; depotForSave.inventory['Produit A'] = 30;
    assert.equal(createManualLogisticsMission(courierForSave.id, depotForSave.id, supplySeller.id, 'Produit A', 5).success, true);
    for (let i = 0; i < 1000 && !getInventoryTotal(courierForSave); i++) updateLogisticsRealtime(.1);
    assert.ok(getInventoryTotal(courierForSave) > 0);
    const inTransit = getNetworkStock().total; assert.equal(saveGame(), true); assert.equal(loadGame(), true);
    assert.equal(game.logisticsMissions.length, 1);
    for (let i = 0; i < 2000 && game.logisticsMissions.length; i++) updateLogisticsRealtime(.1);
    assert.equal(game.logisticsMissions.length, 0); assert.equal(getNetworkStock().total, inTransit);
    const servedCustomer = createCustomer(); Object.assign(servedCustomer, { product: 'Produit A', quantity: 1, price: 12, budget: 20, x: game.playerX, y: game.playerY + 3.2 });
    joinSellerQueue(servedCustomer, getPlayerSeller()); updateCustomersRealtime(.1);
    assert.equal(resolveSale(servedCustomer).success, true); const servedId = servedCustomer.id;
    assert.equal(saveGame(), true); assert.equal(loadGame(), true);
    assert.equal(resolveSale(customers.find(c => c.id === servedId)).success, false);
    renderManagementPanel(); assert.equal(document.getElementById('debugPanel'), null);
    clearWaitingCustomers(); scheduleCustomerSpawn(); updateCustomerSpawning(getDynamicSpawnDelay() / 1000 + .1); assert.equal(customers.length, 1);
    assert.equal(AudioSystem.play('events', 'start'), false);
    assert.equal(AudioSystem.setVolume('police', 2), true); assert.equal(AudioSystem.settings().police, 1);
    assert.equal(AudioSystem.setVolume('unknown', .5), false);
}
