"""Generate runtime data and annotated composition from the shared scene specification."""
import json
from pathlib import Path
from PIL import Image, ImageDraw
ROOT=Path(__file__).resolve().parents[3]
spec=json.loads((Path(__file__).parent/'scene-spec.json').read_text())
(ROOT/'neighborhood-data.js').write_text('// Generated by tools/blender/neighborhood/prepare.py; edit scene-spec.json.\nconst NEIGHBORHOOD_SPEC = '+json.dumps(spec,separators=(',',':'))+';\n')
# A completed composition preview must not be regenerated during resume.
if (ROOT/'assets/art-v2/previews/composition-plan.png').exists():
 raise SystemExit(0)
im=Image.new('RGB',(900,1100),'#101b28');d=ImageDraw.Draw(im)
def xy(x,y):return (450+(x-y)*4.8,65+(x+y)*4.8)
colors=dict(roads='#45505c',courts='#9f947c',parking='#727b86',walls='#deab6d',transitions='#e8d987',buildings='#859aad')
for key,color in colors.items():
 for b in spec[key]:
  pts=[xy(p['x'],p['y']) for p in b['polygon']];d.polygon(pts,fill=color,outline='white')
  if key in ['buildings','courts','transitions']:
   x,y=xy(b['x']+b['width']/2,b['y']+b['height']/2);d.text((x-22,y),b['id'],fill='white')
for q in spec['decor']:
 x,y=xy(q['anchor']['x'],q['anchor']['y']);color='#81aa68' if q['visualType']=='tree' else '#ffcb72' if q['visualType']=='light' else '#b1beca';d.ellipse((x-3,y-3,x+3,y+3),fill=color)
d.text((25,20),'2.6B.2 - Composition annotee / reperes de simulation',fill='white')
d.text((25,1050),'7 barres / 2 cours / murs ocre / arbres verts / lanternes ambre',fill='white')
im.save(ROOT/'assets/art-v2/previews/composition-plan.png')
